import { ActiveSymbols as TActiveSymbols } from 'src/types/api-types';

export const hardcodedActiveSymbols: TActiveSymbols = [
  {
    "allow_forward_starting": 0,
    "display_name": "AUD Basket",
    "display_order": 30,
    "exchange_is_open": 1,
    "is_trading_suspended": 0,
    "market": "synthetic_index",
    "market_display_name": "Derived",
    "pip": 0.001,
    "subgroup": "baskets",
    "subgroup_display_name": "Baskets",
    "submarket": "forex_basket",
    "submarket_display_name": "Forex Basket",
    "symbol": "R_100",
    "symbol_type": "forex_basket",
  },
  {
    "allow_forward_starting": 1,
    "display_name": "AUD/CAD",
    "display_order": 10,
    "exchange_is_open": 1,
    "is_trading_suspended": 0,
    "market": "forex",
    "market_display_name": "Forex",
    "pip": 0.00001,
    "subgroup": "none",
    "subgroup_display_name": "None",
    "submarket": "minor_pairs",
    "submarket_display_name": "Minor Pairs",
    "symbol": "frxAUDCAD",
    "symbol_type": "forex",
  },
];
